### ISSUE TITLE
TasitAction event timeout fix

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#113] opened 2019-01-15 16:59 UTC
As it's now, all alive listeners are throwing error event after the timeout. That's wrong.
Which condition should  be true to emit an error?

@pcowgill comments:
> `> TIMEOUT since last confirmation of the tx`
> So we'd want to remove the previously-set timeout and set a new one on each confirmation

> The goal should be for just one error event to come in when this happens.
> I think the time when it should be thrown is if
> current time - last confirmation block time > CONFIRMATION_TIMEOUT

Refs: https://github.com/tasitlabs/TasitSDK/pull/102#discussion_r247586254 and https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245880280

**Comment by pcowgill** [comment] 2019-01-15 17:14
Oh, and the timer would be set once on the class for an action subscription. Does that make sense?

**Comment by marcelomorgado** [comment] 2019-01-16 10:30
> Oh, and the timer would be set once on the class for an action subscription. Does that make sense?

Each event will have its own time. Is it?

**Comment by pcowgill** [comment] 2019-01-16 15:37
> > Oh, and the timer would be set once on the class for an action subscription. Does that make sense?
> 
> Each event will have its own timer. Is it?

Hmm, I guess we should clarify what type of subscription we're talking about.

For a tx subscription, there's really only one timer that matters - if it's getting confirmed often enough. So that can be a single timer that is reset on each confirmation.

As for events, I'm not sure we even need the ability to set timeouts in this library - that can happen in userland.

**Comment by marcelomorgado** [comment] 2019-01-16 16:39
Got it.

**Comment by pcowgill** [comment] 2019-01-17 15:46
I'm closing this since it was addressed in https://github.com/tasitlabs/TasitSDK/pull/122

**Closed by pcowgill** 2019-01-17 15:46 UTC
Labels: bug
